### PR TITLE
Auto-refresh on swipe to library tab

### PR DESCRIPTION
**Pull request by asadsalman**
Swiping to library tab after downloading song doesn't show latest song.
I've added repopulateList() method (same code as pull-to-refresh) that runs every time you swipe to the LibraryFragment Tab.

### CODE REVIEW

**Comment by AnandChowdhary** [comment]
Don't you think it makes more sense to refresh every time a file finishes downloading?

**Comment by asadsalman** [comment]
True, that is a possible way to do it. 
I went with the lazy approach since you won't have to instantiate and work with the view's adaptor or the songList outside the scope they're used in.

**Comment by AnandChowdhary** [comment]
@prempalsingh, what say?

**Comment by prempalsingh** [comment]
@asadsalman Thanks for sending in the PR. I'll test the changes you made and merge it tonight. Do you think you can implement this using a broadcast receiver so the list gets updated everytime the download complete broadcast is received?
The app hasn't been maintained from a long time so there will a lot of changes as soon as the new backend is done. Will be including in the design library and add Volley via build.gradle instead of the source files etc.

**Comment by asadsalman** [comment]
I understand a possible concern you may have, you don't want to update the list if no song has been added. I took care of that in this commit by using a boolean that is checked before updating the list. This boolean is set true with every successful download.

I tried going with your approach too, but honestly couldn't find any way to do it without leading to repetitive code. One possible approach I investigated was using adding a static function in LibraryFragment that would do everything getSongList() does, only statically, so that it can be called from DownloadReceiver too. Like I said, that would require repetitive code.

It's very possible that I'm missing something. Do point out if I am.

Any suggestions would be appreciated!

**Comment by prempalsingh** [comment]
@asadsalman  There is a possibility that the app has stopped but the download is still running. In that case, your implementation will give a null pointer error. What I had in mind was a dynamic broadcast receiver in the library fragment that refreshes the list when the DOWNLOAD_COMPLETE broadcast is received if the recyclerview is not null.

**Comment by asadsalman** [comment]
Oh. Really sorry, but I didn't know of dynamic broadcast receivers. Being self-taught, I surely may have missed a few things.
After looking up dynamic broadcast receivers, I realize that this approach would be much better.

Let me cook up an implementation and submit. I'll try to get it done today.

Thanks!

**Comment by prempalsingh** [comment]
Hey, no worries. Even I didn't, back when I made this. :D

**Comment by asadsalman** [comment]
So, what do you guys think of the new patch?
Would love any feedback to improve it.

**Comment by prempalsingh** [comment]
Sorry for the late reply. Will have a look when I am back in town.

**Comment by prempalsingh** [comment]
@asadsalman Sorry, I completely forgot about this. This should work but there's no need of catching the broadcast first in the DownloadReceiver and then sending it again as a local broascast. You can directly receive the original broadcast in the LibraryFragment.

**Comment by asadsalman** [comment]
I couldn't find any Intent being broadcast on download complete, could you point it out?

**Comment by prempalsingh** [comment]
@asadsalman Instead of using the LocalBroadcastManager, you can use a normal BroadcastManager to catch the DownloadManager.ACTION_DOWNLOAD_COMPLETE broadcast. The broadcast will be received only if the fragment is in resumed state. LocalBroadcastManager is generally used when you want to send custom broadcasts to internal components.

**Pull request closed without merging**
